[package]
name = "road-network-json"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = "0.36"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
proj4rs = "0.1"
anyhow = "1.0"
